name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Snake Animation
      - name: Generate snake animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: michelleGomes85
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit and push changes
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
